// Do not Edit this file.

params ["_player", "_didJIP"];

// Disables ambient animals and ambient sounds
[{time > 0}, {enableEnvironment [false, true];}] call CBA_fnc_waitUntilAndExecute;

[_player, specScreen] call MFUNC(baseSpectator);
[_player] call FUNC(briefing);
[_player] call MFUNC(godMode);
[_player] call MFUNC(unconscious);

// Set local player time until start (0 if debug mode enabled)
#ifdef DEBUG_MODE_FULL
GVAR(timeUntilStartPlayer) = 0;
#else
GVAR(timeUntilStartPlayer) = call MFUNC(timeUntilStart);
#endif

INFO_1("Time Until Start Player: %1",GVAR(timeUntilStartPlayer));

// Mission name event
[QGVAR(missionName), {
    [
        [
            [getMissionConfigValue ["onLoadName", ""], "<t size = '1.5' underline = '1'>%1</t><br/>"],
            ["Theseus Incorporated"],
            [getText (configFile >> "CfgWorlds" >> worldName >> "description"), "<t size = '1' font='puristaSemiBold'>%1</t>", 70]
        ]
    ] spawn BIS_fnc_typeText;
}] call CBA_fnc_addEventHandler;

// Chat Commands
["tac-aar", {
    [QMGVAR(manualAAR), _thisArgs] call CBA_fnc_serverEvent;
}, "admin", [_player]] call CBA_fnc_registerChatCommand;

// Vehicle Spawner List
GVAR(vehicleSpawnerList) = [
    "tacs_Arcadian_B_Black", // Arcadians
    "tacs_Arcadian_B_Green",
    "tacs_Arcadian_B_Grey",
    "tacs_Arcadian_B_Tan",
    "tacs_HEMTT_B_Transport", // HEMTT Transport
    "tacs_Offroad_B_Black", // Offroad
    "tacs_Offroad_B_Covered_Black",
    "tacs_Polaris_B_Black", // Polaris DAGOR
    "tacs_Polaris_B_Green",
    "tacs_Polaris_B_Tan",
    "tacs_Van_Cargo_B_Black", // Van
    "tacs_Van_Transport_B_Black"
];

[TemplateVehicleSpawner, TemplateVehiclePosition] call MFUNC(vehicleSpawner);
