// Do not Edit this file.

// Broadcast staff userconfig to clients
MGVAR(admins) = [ADMINS];
publicVariable QMGVAR(admins);
MGVAR(debug_admins) = [DEBUG_ADMINS];
publicVariable QMGVAR(debug_admins);

// Mathematical heresy
#ifdef DEBUG_MODE_FULL
GVAR(timeUntilStart) = 0;
INFO("Debug Enabled: Time Until Start set to 0");
#else
systemTimeUTC params ["", "", "", "_hour", "_minute"];
private _startTime = 14; // 1400z always
GVAR(timeUntilStart) = ((_startTime * 60) - (_hour * 60 + _minute)) * 60; // start time - current time = time until start time
GVAR(timeUntilStart) = GVAR(timeUntilStart) max 0;
INFO_1("Time Until Start: %1",GVAR(timeUntilStart));
#endif

publicVariable QGVAR(timeUntilStart);

// AAR
[GVAR(timeUntilStart)] call MFUNC(aar);

// Mission Name call on mission start
[{
    [QGVAR(missionName), []] call CBA_fnc_globalEvent;
}, [], GVAR(timeUntilStart) + 60] call CBA_fnc_waitAndExecute;
