// Do not Edit this file.

// Verify staff userconfig was loaded
if (!is3DENPreview && {MGVAR(admins) isEqualTo [] || {MGVAR(debug_admins) isEqualTo []}}) then {
    ERROR_MSG("Empty ADMINS or DEBUG_ADMINS! Userconfig missing or failed to load!");
};

 // Verify mission type is correct
private _missionType = getMissionConfigValue ["tac_type", -1];
if (_missionType == -1 || {_missionType >= count MISSION_TYPES}) exitWith {
    ERROR_MSG_2("Invalid mission type %1! Expected 0-%2",_missionType,count MISSION_TYPES - 1);
};

// Sets ACRE2 channel names
{
    [_x, "default", "theseus"] call acre_api_fnc_copyPreset;
    [_x, "theseus", 1, "label", "ARES 1"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 2, "label", "ARES 2"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 3, "label", "ARES 3"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 4, "label", "ARES 4"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 5, "label", "COMMAND"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 11, "label", "HELIOS 1"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 12, "label", "HELIOS 2"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 13, "label", "HELIOS 3"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 14, "label", "HELIOS 4"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus", 15, "label", "HELIOS CMND"] call acre_api_fnc_setPresetChannelField;
    [_x, "theseus"] call acre_api_fnc_setPreset;
} forEach ["ACRE_PRC152", "ACRE_PRC117F"];
