// Do not Edit this file.

#define PREFIX TAC
#define COMPONENT Scripts

// Version
#define MAJOR 3
#define MINOR 6
#define PATCHLVL 2

// Debug
#define DEBUG_SYNCHRONOUS

#include "script_macros_mission.hpp"
