// Do not Edit this file.

#define PREFIX TAC
#define COMPONENT Scripts

// Version
#define MAJOR 3
#define MINOR 6
#define PATCHLVL 2

// Debug
#define DEBUG_SYNCHRONOUS

#include "script_macros_mission.hpp"

// Userconfig
// __has_include requires -filePatching (which also prevents clients to load their local userconfig as they can't join with file patching)
// __has_include is not supported by HEMTT so we do it in the template for now
#if __has_include("\userconfig\tac\staff.hpp")
    #include "\userconfig\tac\staff.hpp"
#endif
#ifndef ADMINS
    #define ADMINS
#endif
#ifndef DEBUG_ADMINS
    #define DEBUG_ADMINS
#endif
