// Do not Edit this file.

// Disables ambient animals and ambient sounds
[{time > 0}, {enableEnvironment [false, true];}] call CBA_fnc_waitUntilAndExecute;

[_player, specScreen] call FUNC(baseSpectator);
[_player] call FUNC(briefing);
[_player] call FUNC(godMode);

// Disable CUP street lights based on lighting levels (bad performance script)
CUP_stopLampCheck = true;
