// Do not Edit this file.

// Log given traits to RPT 70 minutes after mission start.
[{
    private _playerTraits = [];
    {
        _playerTraits pushBack [_x, _y];
    } forEach TACGVAR(supplies,playerTraits);
    INFO_1("Player Traits: %1",_playerTraits); // For now just logging to RPT, future uses TBD.
}, [], 4200] call CBA_fnc_waitAndExecute;
