// Do not Edit this file.

[_player, specScreen] call FUNC(baseSpectator);
[_player] call FUNC(briefing);

// Disable CUP street lights based on lighting levels (bad performance script)
CUP_stopLampCheck = true;
