name: Package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Package
      run: |
        echo "Rename"
        mv guide Theseus_Mission_Making_Guide.VR
        echo "Version"
        MAJOR=$(grep -oP "#define MAJOR \K(\d+)" template/script_component.hpp)
        MINOR=$(grep -oP "#define MINOR \K(\d+)" template/script_component.hpp)
        PATCH=$(grep -oP "#define PATCHLVL \K(\d+)" template/script_component.hpp)
        echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $env:GITHUB_ENV
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TAC-Mission-Template_$VERSION
        path: |
          compositions
          guide
          scripts
          template
          LICENSE
          README.md
    - name: Upload to GitHub
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: true
        files: "*.zip"
        name: "TAC Mission Template $VERSION"
        tag_name: v$VERSION
